robot:
  type: openk-1-alpha_follower2 #ロボットの種類
  port: COM5
  sts_port: COM10
  id: hogehogerobot #ロボットの個体識別名
  #calibration_dir: null #calibration_dirは今後使わない。
  calibration_root: calib
  cameras: {}
